[package]
description = "library for building integration testing environments for cosmos-sdk chains in Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "test-tube"
repository = "https://github.com/osmosis-labs/test-tube"
version = "0.1.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
cosmrs = { git = "https://github.com/oraichain/cosmos-rust.git", features = [
    "cosmwasm",
    "rpc",
], rev = "061d0ec" }
cosmwasm-std = { workspace = true, features = ["stargate"] }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde-json-wasm = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
cw1-whitelist = { workspace = true }
rayon = { workspace = true }

[features]
default = []

module-wrappers = ["bank", "wasm"]
wasm-sudo = []
bank = []
wasm = []
